project:
  type: website
  output-dir: docs

website:
  title: "Project - Social Isolation"
  navbar:
    left:
      - href: wiki/pages/index.qmd
        text: Home
      - wiki/pages/about.qmd
      - papers/papers.qmd

format:
  html:
    theme: 
    - cosmo
    - wiki/styles/custom.scss
    css: wiki/styles/styles.css
    toc: true



