project:
  type: website
  output-dir: docs

website:
  title: "Study - Social Isolation"
  navbar:
    left:
      - href: wiki/pages/index.qmd
        text: Home
      - wiki/pages/about.qmd

format:
  html:
    theme: cosmo
    css: wiki/styles/styles.css
    toc: true



